# Generated by Django 4.0.4 on 2022-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='math',
            name='user_input',
            field=models.IntegerField(blank=True),
        ),
    ]
