# Generated by Django 4.0.4 on 2022-05-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_game', '0002_math_session_key_alter_math_user_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math',
            name='user_input',
        ),
    ]
