# Generated by Django 4.0.4 on 2022-05-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_game', '0004_alter_math_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='rounds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
